--DML- INSERIR DADOS NAS TABELAS

--USAR O BANCO CRIADO
USE Exercicio_1_1;

--INSERIR DADOS NA TABELA
INSERT INTO Pessoa(Nome,CNH)
VALUES('Carlos','1234343256'),('Eduardo','8878064369')

INSERT INTO Email (IdPessoa,Endereco)
VALUES(1,'carlos2@gmail.com')


INSERT INTO Telefone(IdPessoa,Numero)
VALUES(1,'37305705')

SELECT * FROM Telefone

SELECT * FROM Pessoa
SELECT * FROM Email
